version: '2'
volumes:
  redisvol:
services:
  web:
    build: .
    command: python app.py
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "us-east-2"
           awslogs-group: "newlog"
           awslogs-stream: "flaskapp"
    ports:
     - "3050:5000"
  redis:
    image: "redis:alpine"
     logging:
        driver: "awslogs"
        options:
           awslogs-region: "us-east-2"
           awslogs-group: "newlog"
           awslogs-stream: "redis"
    volumes:
       - redisvol:/data
